networks:
  edgex-network:
    driver: bridge
services:

#################################################################
# TIBCO Labs Air
#################################################################

  service-zmq-to-mqtt:
    image: tibcosoftware/labs-air-edgex-app-service-zmq-to-mqtt:latest
    ports:
      - "48540:48540"
    container_name: air-app-service-zmq-to-mqtt
    hostname: air-app-service-zmq-to-mqtt
    networks:
      - edgex-network
    environment:
      REGISTRY_HOST: ${EDGEX_CORE_CONSUL}
      CLIENTS_COREDATA_HOST: ${EDGEX_CORE_DATA_HOST}
      CLIENTS_DATA_HOST: ${EDGEX_CORE_DATA_HOST}
      CLIENTS_NOTIFICATIONS_HOST: ${EDGEX_SUPPORT_NOTIFICATIONS}
      CLIENTS_METADATA_HOST: ${EDGEX_CORE_METADATA}
      CLIENTS_COMMAND_HOST: ${EDGEX_CORE_COMMAND}
      CLIENTS_SCHEDULER_HOST: ${EDGEX_SUPPORT_SCHDELER}
      CLIENTS_VIRTUALDEVICE_HOST: ${EDGEX_DEVICE_VIRTUAL}
      DATABASES_PRIMARY_HOST: ${EDGEX_REDIS}
      EDGEX_SECURITY_SECRET_STORE: "false"
      BINDING_TYPE: edgex-messagebus
      BINDING_SUBSCRIBETOPIC: events
      BINDING_PUBLISHTOPIC: somewhere
      MESSAGEBUS_TYPE: zero
      MESSAGEBUS_SUBSCRIBEHOST_HOST: ${EDGEX_CORE_DATA_HOST}
      MESSAGEBUS_SUBSCRIBEHOST_PORT: 5563
      MESSAGEBUS_OPTIONAL_CLIENTID: air-app-service-zmq-to-mqtt
      SERVICE_HOST: ${AIR_APP_SERVICE_ZMQ_TO_MQTT}
      SERVICE_PORT: 48540
      WRITABLE_LOGLEVEL: DEBUG
      ApplicationSettings_MqttHostname: ${EDGE_MQTT_HOSTNAME}
      ApplicationSettings_MqttPort: ${EDGE_MQTT_PORT}
      ApplicationSettings_MqttUser: ${EDGE_MQTT_USER}
      ApplicationSettings_MqttPassword: ${EDGE_MQTT_PASSWORD}
      ApplicationSettings_MqttTopic: ${EDGE_MQTT_DATA_TOPIC}
      ApplicationSettings_MqttPublisher: ${EDGE_MQTT_ZMQ_TO_MQTT_PUBLISHER}
      ApplicationSettings_GatewayId: ${GATEWAY_ID}
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  service-metadata:
    image: tibcosoftware/labs-air-edgex-app-service-metadata:latest
    ports:
      - "48530:48530"
    container_name: air-app-service-metadata
    hostname: air-app-service-metadata
    networks:
      - edgex-network
    environment:
      REGISTRY_HOST: ${EDGEX_CORE_CONSUL}
      CLIENTS_COREDATA_HOST: ${EDGEX_CORE_DATA_HOST}
      CLIENTS_DATA_HOST: ${EDGEX_CORE_DATA_HOST}
      CLIENTS_NOTIFICATIONS_HOST: ${EDGEX_SUPPORT_NOTIFICATIONS}
      CLIENTS_METADATA_HOST: ${EDGEX_CORE_METADATA}
      CLIENTS_COMMAND_HOST: ${EDGEX_CORE_COMMAND}
      CLIENTS_SCHEDULER_HOST: ${EDGEX_SUPPORT_SCHDELER}
      CLIENTS_VIRTUALDEVICE_HOST: ${EDGEX_DEVICE_VIRTUAL}
      DATABASES_PRIMARY_HOST: ${EDGEX_REDIS}
      EDGEX_SECURITY_SECRET_STORE: "false"
      BINDING_TYPE: edgex-messagebus
      BINDING_SUBSCRIBETOPIC: events
      BINDING_PUBLISHTOPIC: somewhere
      MESSAGEBUS_TYPE: zero
      MESSAGEBUS_SUBSCRIBEHOST_HOST: ${EDGEX_CORE_DATA_HOST}
      MESSAGEBUS_SUBSCRIBEHOST_PORT: 5563
      MESSAGEBUS_OPTIONAL_CLIENTID: air-app-service-metadata
      SERVICE_HOST: ${AIR_APP_SERVICE_METADATA}
      SERVICE_PORT: 48530
      WRITABLE_LOGLEVEL: DEBUG
      ApplicationSettings_MqttHostname: ${AIR_MQTT_HOSTNAME}
      ApplicationSettings_MqttPort: ${AIR_MQTT_PORT}
      ApplicationSettings_MqttUser: ${AIR_MQTT_USER}
      ApplicationSettings_MqttPassword: ${AIR_MQTT_PASSWORD}
      ApplicationSettings_MqttTopic: ${AIR_MQTT_DATA_TOPIC}
      ApplicationSettings_MqttPublisher: ${AIR_MQTT_DATA_METADATA_PUBLISHER}
      ApplicationSettings_GatewayId: ${GATEWAY_ID}
      ApplicationSettings_GatewayDescription: ${GATEWAY_DESCRIPTION}
      ApplicationSettings_GatewayHostname: ${GATEWAY_HOSTNAME}
      ApplicationSettings_GatewayRouter: ${GATEWAY_ROUTER}
      ApplicationSettings_GatewayRouterPort: ${GATEWAY_ROUTER_PORT}
      ApplicationSettings_GatewayDeployNetwork: ${GATEWAY_DEPLOY_NETWORK}
      ApplicationSettings_GatewayLatitude: ${GATEWAY_LATITUDE}
      ApplicationSettings_GatewayLongitude: ${GATEWAY_LONGITUDE}
      ApplicationSettings_GatewayAccessToken: ${GATEWAY_ACCESS_TOKEN}
      ApplicationSettings_GatewayUsername: ${GATEWAY_USERNAME}
      ApplicationSettings_GatewayPlatform: ${GATEWAY_PLATFORM}
      ApplicationSettings_MetadataClient: ${GATEWAY_METADATA_CLIENT}
      ApplicationSettings_MetadataPublishIntervalSecs: ${GATEWAY_METADATA_PUBLISH_INTERVAL_SECS}
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
  
#  device-siemens-simulator:
#    image: tibcosoftware/labs-air-edgex-device-siemens-simulator:latest
#    ports:
#      - "48995:48995"
#    container_name: labsair-device-siemens-simulator
#    hostname: labsair-device-siemens-simulator
#    networks:
#      - edgex-network
#    environment:
#      REGISTRY_HOST: ${EDGEX_CORE_CONSUL}
#      CLIENTS_COREDATA_HOST: ${EDGEX_CORE_DATA_HOST}
#      CLIENTS_DATA_HOST: ${EDGEX_CORE_DATA_HOST}
#      CLIENTS_NOTIFICATIONS_HOST: ${EDGEX_SUPPORT_NOTIFICATIONS}
#      CLIENTS_METADATA_HOST: ${EDGEX_CORE_METADATA}
#      CLIENTS_COMMAND_HOST: ${EDGEX_CORE_COMMAND}
#      CLIENTS_SCHEDULER_HOST: ${EDGEX_SUPPORT_SCHDELER}
#      DATABASES_PRIMARY_HOST: ${EDGEX_REDIS}
#      EDGEX_SECURITY_SECRET_STORE: "false"
#      SERVICE_HOST: ${LABAIR_DEVICE_SIEMENS_SIMULATOR}
#      SERVICE_PORT: 48995
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data


version: '3.7'
volumes:
  consul-config: {}
  consul-data: {}
  consul-scripts: {}
  db-data: {}
  log-data: {}
